// <auto-generated />
using System;
using Bank1.Service.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bank1.Service.Infrastructure.Persistence.AuditMigrations
{
    [DbContext(typeof(Bank1AuditDbContext))]
    [Migration("20260811051824_InitialAuditCreate")]
    partial class InitialAuditCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Bank1.Service.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("account_number");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("balance");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("currency");

                    b.Property<string>("HolderName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("holder_name");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("opened_at");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_account_number");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Bank1.Service.Infrastructure.Persistence.Entities.AuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ActorSubject")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("actor_subject");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("correlation_id");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_code");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("event_type");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("metadata_json");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("operation");

                    b.Property<string>("RequestId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("request_id");

                    b.Property<string>("ResourceId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("resource_type");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("service_name");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER")
                        .HasColumnName("success");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.Property<string>("TraceId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("trace_id");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_audit_records_correlation_id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_audit_records_timestamp");

                    b.ToTable("audit_records", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
